# Overriding setting for dev
exclude: [node_modules, gulpfile.js, gulpconfig.js, package.json, bower_components, bower.json]

collections:
  # This is where all out test pages will go
  tests:
    output: true
