# Site settings
title: Joey Hayes
email: bjoeyhayes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://yourdomain.com" # the base hostname TODO: Update this before site goes live

# Social Media - Sharing
fb-app_id:
twitter_username: bjoeyhayes
github_username:  joeyred

# Paths
images:
  posts: /assets/imgs/posts
  projects: /assets/imgs/projects

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json]
keep_files: [assets]

# Content
collections:
  # Projects Config
  projects:
    output: true
    # permalink: /portfolio/:path/
  # Styleguide
  styleguide:
    label: Styleguide

# Set More Defaults
defaults:
  - # This is needed between each `scope`
    scope:
      path: "" # an empty string here means all files in the project
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      og_type: article
# Icons
icons:
  menu: <svg><use xlink:href="#menu"></use></svg>
  close: <svg><use xlink:href="#close"></use></svg>
  behance: <svg><use xlink:href="#behance"></use></svg>
  codepen: <svg><use xlink:href="#codepen"></use></svg>
  github: <svg><use xlink:href="#github"></use></svg>
  facebook: <svg><use xlink:href="#facebook"></use></svg>
  twitter: <svg><use xlink:href="#twitter"></use></svg>
  linkedin: <svg><use xlink:href="#linkedin"></use></svg>
  instagram: <svg><use xlink:href="#instagram"></use></svg>
  googleplus: <svg><use xlink:href="#googleplus"></use></svg>
  stackoverflow: <svg><use xlink:href="#stackoverflow"></use></svg>
