title: Brian Hayes
description: >
  The personal professional website and portfolio for Brian Hayes.
url: https://www.brianhayes.me
# url: https://joeyred.github.io/mysite
email: bjoeyhayes@gmail.com
social:
  twitter: https://twitter.com/BrianDoesCode
  linkedin: https://www.linkedin.com/in/briandoescode/
  github: https://github.com/joeyred
  codepen: https://codepen.io/joeyred/
  stackoverflow: https://stackoverflow.com/story/brianhayes

servers:
  port: 8000

# Directories
source: src
destination: build
templates: metalsmith
styles: scss
data: content
# Content
data_files:
  - treehouse.json
  - skills.yml
  - authors.yml
collections:
  # Posts
  posts:
    output: true
    defaults:
      type: 'pen'
      extends: '../../layouts/post.pug'
      author: brianhayes
  # Pens
  pens:
    output: true
    defaults:
      type: 'pen'
      api:
        namespace: 'pens'
  # Projects
  projects:
    output: true
    defaults:
      type: 'project'
      api:
        namespace: 'projects'
  # Styleguide
  styleguide:
    output: false
    precompile: true
  # Documentation
  docs:
    output: true
    defaults:
      type: 'doc'
      api:
        namespace: 'docs'
assets:
  # whether to use an /assets/ sub directory
  sub_dir: true
  # Styles
  styles:
    destination: css
    compatability:
      - last 2 versions
      - ie >= 9
      - safari 8
    include_directories:
      - base
      - components
      - ui-modules
      - pages
      - projects

  # Scripts
  scripts:
    partials:
      - modules/core.js
      - modules/util.*.js
      - '**/!(app).js'
      - app.js

  # Images
  images:
    optimization: 7

tests:
  scripts:
    partials:
      - modules/core.js
      - modules/util.*.js
      - modules/**.js
