title: Brian Hayes
description: >
  The personal professional website and portfolio for Brian Hayes.
url: http://brianhayes.me
email: bjoeyhayes@gmail.com
social:
  twitter: https://twitter.com/BJoeyHayes
  linkedin: https://www.linkedin.com/in/bjoeyhayes/
  github: https://github.com/joeyred
  codepen: https://codepen.io/joeyred/
  stackoverflow: https://stackoverflow.com/users/5331958/joeyred

servers:
  port: 8000

source: src
destination: build
templates: metalsmith
styles: scss
# Content
collections:
  # Pens
  pens:
    output: true
    defaults:
      type: 'pen'
  # Projects
  projects:
    output: true
    defaults:
      type: 'project'
  # Styleguide
  styleguide:
    precompile: true
  # Documentation
  docs:

assets:
  # whether to use an /assets/ sub directory
  sub_dir: true
  # Styles
  styles:
    destination: css
    compatability:
      - last 2 versions
      - ie >= 9
      - safari 8
    include_directories:
      - base
      - components
      - pages
      - projects


  # Scripts
  scripts:
    partials:
      - modules/core.js
      - modules/util.*.js
      - '**/!(app).js'
      - app.js
    test:
      partials:
        - modules/core.js
        - modules/util.*.js
        - modules/**.js

  # Images
  images:
    optimization: 7
